from .fast_abscoef import absorptionCoefficient_Voigt
from .fast_abscoef import absorptionCoefficient_Lorentz
from .fast_abscoef import absorptionCoefficient_Doppler
from .fast_abscoef import absorptionCoefficient_Generic